---
AWSTemplateFormatVersion: 2010-09-09


Description: >
  This template shows how to use AWS CodePipeline and AWS CodeBuild to build an
  automated continuous integration pipeline from GitHub to Docker Images.


Parameters:
  GitHubUser:
    Type: String
    Description: Your username on GitHub.

  GitHubRepo:
    Type: String
    Default: demorailsapp
    Description: The repo name of the source code for your image.

  GitHubBranch:
    Type: String
    Default: master
    Description: The branch of the repo to build and automate.

  GitHubToken:
    Type: String
    NoEcho: true
    Description: >
      A Deploy Key scoped for the repo specified above, with at least read access.

  DockerUpstream:
    Type: String
    Default: kingdonb/rails:postgresql
    Description: >
      The Dockerfile downstream's FROM setting.

  TemplateBucket:
    Type: String
    Default: kingdonb-refarch-continuous-deployment
    Description: >
      The S3 bucket from which to fetch the templates used by this stack.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      GitHubUser:
        default: "User"
      GitHubRepo:
        default: "Repo"
      GitHubBranch:
        default: "Branch"
      GitHubToken:
        default: "Personal Access Token"
      DockerUpstream:
        default: "Upstream Docker Repo"
    ParameterGroups:
      - Label:
          default: Image Build Configuration
        Parameters:
          - GitHubRepo
          - GitHubBranch
          - GitHubUser
          - GitHubToken
      - Label:
          default: Stack Configuration
        Parameters:
          - TemplateBucket


Resources:
  DeploymentPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplateBucket}/templates/deployment-pipeline.yaml"
      Parameters:
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch
        DockerUpstream: !Ref DockerUpstream



Outputs:
  PipelineUrl:
    Description: The continuous deployment pipeline in the AWS Management Console.
    Value: !GetAtt DeploymentPipeline.Outputs.PipelineUrl
